### ISSUE TITLE
get the audio data

### ISSUE THREAD

**Issue by pengqin** [jpikl/cfxnes#7]
How can I get the audio data of cfxnes?
if i want send the audio data to other machine through network

**Comment by jpikl** [comment]
Currently there is no API for that but it should not be difficult to implement.

I see two options:

1. A callback function that would be called every time audio data are generated.

2. Option to provide own audio context. This way you could use OfflineAudioContext to process the generated audio data.

This also depends on whether you need to receive audio data as soon as they are generated by emulation or you need to receive them at constants rate. Cfxnes contains an internal audio buffer to compensate difference between emulation speed and constant rate audio is processed.

**Comment by pengqin** [comment]
thank you.
The option1: A callback function that would be called every time audio data are generated
what is the callback function,  or  need to update the source code?

**Comment by jpikl** [comment]
No there is no such callback.
I might implemented it, but I am quite busy right now.

If you want to implement it yourself, the best place to start is in `swapBuffers` method in `core/src/audio/APU.js` where you would pass generated data to the callback function.

**Comment by pengqin** [comment]
ok thank you。
I test cfxnes on mobile， is slowly.
I want run cfxnes in webwork,   so , if I want  renderer  and audio through postMessage, which file is the main loop?  ,

**Comment by jpikl** [comment]
Yes, cfxnes performs poorly on mobile devices, I am aware of that.

I am not sure cfxnes is going to work in web worker since it might need some browser functions that are not available there. I haven't tested it though.

In your case it might be better to use cfxnes low-level API from core module that does not depend on any browser functions. There is no build or npm package for it, so you will have to include its sources in your project. But I have to warn you that the core API is currently unstable and undocumented. There are [some examples ](https://github.com/jpikl/cfxnes/blob/master/core/README.md) how to use it, but you will probably have to dig through source code to see how it works.

**Comment by jpikl** [comment]
I did some refactoring and you can now register a callback function to receive generated audio samples. See [example](https://github.com/jpikl/cfxnes/blob/master/core/README.md#audio-output)

If you care about performance, you should try [jsnes](https://github.com/bfirsh/jsnes) instead of cfxnes.
